spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: eapor
    password: eapor
    url: jdbc:mysql://123.57.248.31:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: D:\log
#  file: D:\log\sell.log